package com.wudi.community.mapper;

import com.wudi.community.model.Post;
import com.wudi.community.model.PostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    long countByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    int deleteByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    int insert(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    int insertSelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    List<Post> selectByExampleWithBLOBsWithRowbounds(PostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    List<Post> selectByExampleWithBLOBs(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    List<Post> selectByExampleWithRowbounds(PostExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    List<Post> selectByExample(PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    Post selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    int updateByExampleSelective(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    int updateByExample(@Param("record") Post record, @Param("example") PostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    int updateByPrimaryKeySelective(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Post record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table POST
     *
     * @mbg.generated Fri Jan 03 09:47:02 EST 2020
     */
    int updateByPrimaryKey(Post record);
}